---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openstack
  name: configmap-update
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - swift-edpm-inventory
  verbs:
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-update
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-update
subjects:
- kind: ServiceAccount
  name: default
  namespace: openstack
