# permissions for end users to view swiftrings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftring-viewer-role
rules:
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftrings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftrings/status
  verbs:
  - get
