# permissions for end users to edit swiftproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftproxy-editor-role
rules:
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies/status
  verbs:
  - get
