# permissions for end users to view swiftproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftproxy-viewer-role
rules:
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftproxies/status
  verbs:
  - get
