# permissions for end users to view swiftstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftstorage-viewer-role
rules:
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - swift.openstack.org
  resources:
  - swiftstorages/status
  verbs:
  - get
