apiVersion: swift.openstack.org/v1beta1
kind: SwiftProxy
metadata:
  name: swiftproxy-sample
spec:
  swiftRingConfigMap: swiftring-sample-ring-data
  replicas: 1
  secret: osp-secret
  serviceUser: swift
  passwordSelector: SwiftPassword
  containerImageProxy: quay.io/podified-antelope-centos9/openstack-swift-proxy-server:current-podified
  containerImageMemcached: quay.io/podified-antelope-centos9/openstack-memcached:current-podified
