apiVersion: swift.openstack.org/v1beta1
kind: SwiftStorage
metadata:
  name: swiftstorage-sample
spec:
  storageClass: local-storage
  storageRequest: 10G
  replicas: 3
  ringConfigMap: swift-ring-data
  swiftConfSecret: swiftconf
  containerImageAccount: quay.io/podified-antelope-centos9/openstack-swift-account:current-podified
  containerImageContainer: quay.io/podified-antelope-centos9/openstack-swift-container:current-podified
  containerImageObject: quay.io/podified-antelope-centos9/openstack-swift-object:current-podified
  containerImageProxy: quay.io/podified-antelope-centos9/openstack-swift-proxy-server:current-podified
  containerImageMemcached: quay.io/podified-antelope-centos9/openstack-memcached:current-podified
