apiVersion: swift.openstack.org/v1beta1
kind: Swift
metadata:
  name: swift
  namespace: openstack
spec:
  swiftRing:
    replicas: 3
    devices: 3
    containerImage: quay.io/tripleozedcentos9/openstack-swift-proxy-server:current-tripleo
    storagePodPrefix: swift-storage
    storageServiceName: swift-storage

  swiftStorage:
    replicas: 3
    storageClassName: "local-storage"
    swiftRingConfigMap: swift-ring-ring-data
    containerImageAccount: quay.io/tripleozedcentos9/openstack-swift-account:current-tripleo
    containerImageContainer: quay.io/tripleozedcentos9/openstack-swift-container:current-tripleo
    containerImageObject: quay.io/tripleozedcentos9/openstack-swift-object:current-tripleo
    containerImageProxy: quay.io/tripleozedcentos9/openstack-swift-proxy-server:current-tripleo
    containerImageMemcached: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo

  swiftProxy:
    replicas: 1
    passwordSelector: SwiftPassword
    serviceUser: swift
    secret: osp-secret
    swiftRingConfigMap: swift-ring-ring-data
    containerImageProxy: quay.io/tripleozedcentos9/openstack-swift-proxy-server:current-tripleo
    containerImageMemcached: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo
