apiVersion: swift.openstack.org/v1beta1
kind: SwiftProxy
metadata:
  name: swiftproxy-sample
spec:
  swiftRingConfigMap: swiftring-sample-ring-data
  replicas: 1
  secret: osp-secret
  serviceUser: swift
  passwordSelector: SwiftPassword
