apiVersion: swift.openstack.org/v1beta1
kind: SwiftStorage
metadata:
  name: swiftstorage-sample
spec:
  swiftRingConfigMap: swiftring-sample-ring-data
  storageClassName: "local-storage"
  replicas: 3
