apiVersion: swift.openstack.org/v1beta1
kind: SwiftRing
metadata:
  name: swiftring-sample
spec:
  replicas: 3
  devices: 3
  containerImage: quay.io/tripleozedcentos9/openstack-swift-proxy-server:current-tripleo
  storagePodPrefix: swiftstorage-sample
  storageServiceName: swiftstorage-sample
