apiVersion: swift.openstack.org/v1beta1
kind: SwiftProxy
metadata:
  name: swift-proxy
spec:
  replicas: 1
  swiftConfSecret: swift-conf
  secret: osp-secret
  serviceUser: swift
  passwordSelectors:
    service: SwiftPassword
