apiVersion: swift.openstack.org/v1beta1
kind: SwiftProxy
metadata:
  name: swiftproxy-sample
spec:
  swiftRingConfigMap: swiftring-sample-ring-data
  containerImageProxy: quay.io/tripleozedcentos9/openstack-swift-proxy-server:current-tripleo
  containerImageMemcached: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo
  replicas: 1
  secret: keystone-secret
  serviceUser: swift
  passwordSelector: SwiftPassword
