apiVersion: swift.openstack.org/v1beta1
kind: Swift
metadata:
  name: swift
spec:
  swiftRing:
    ringReplicas: 3
    containerImage: quay.io/podified-antelope-centos9/openstack-swift-proxy-server:current-podified
  swiftStorage:
    replicas: 3
    containerImageAccount: quay.io/podified-antelope-centos9/openstack-swift-account:current-podified
    containerImageContainer: quay.io/podified-antelope-centos9/openstack-swift-container:current-podified
    containerImageObject: quay.io/podified-antelope-centos9/openstack-swift-object:current-podified
    containerImageProxy: quay.io/podified-antelope-centos9/openstack-swift-proxy-server:current-podified
    containerImageMemcached: quay.io/podified-antelope-centos9/openstack-memcached:current-podified
  swiftProxy:
    replicas: 1
    containerImageAccount: quay.io/podified-antelope-centos9/openstack-swift-account:current-podified
    containerImageContainer: quay.io/podified-antelope-centos9/openstack-swift-container:current-podified
    containerImageObject: quay.io/podified-antelope-centos9/openstack-swift-object:current-podified
    containerImageProxy: quay.io/podified-antelope-centos9/openstack-swift-proxy-server:current-podified
    containerImageMemcached: quay.io/podified-antelope-centos9/openstack-memcached:current-podified
